# Generated by Django 4.2.14 on 2024-07-31 18:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SentimentData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("crypto", models.CharField(max_length=10)),
                ("date", models.DateField()),
                ("sentiment_score", models.FloatField()),
                ("price", models.FloatField()),
                ("recommendation", models.CharField(max_length=10)),
            ],
        ),
    ]
