# Generated by Django 4.2.14 on 2024-07-31 19:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_sentimentdata_graph"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sentimentdata",
            name="graph",
            field=models.TextField(default=""),
        ),
    ]
